/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    
    // Apply the java-library plugin to add support for Java Library
    `java-library`
    
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
    
    
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

javafx {
    version = "23"                           // o la que uses
    modules("javafx.controls", "javafx.fxml")
}

application {
    mainClass.set("Modelo.App")         // ajusta a tu paquete/clase
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    
    // https://mvnrepository.com/artifact/org.openjfx/javafx-controls
	implementation("org.openjfx:javafx-controls:17.0.2")
	
	// https://mvnrepository.com/artifact/org.openjfx/javafx-graphics
	implementation("org.openjfx:javafx-graphics:17.0.2")

    // https://mvnrepository.com/artifact/org.openjfx/javafx-fxml
    implementation("org.openjfx:javafx-fxml:17.0.2")
    
    // https://mvnrepository.com/artifact/org.openjfx/javafx-base
	implementation("org.openjfx:javafx-base:17.0.2")
	
	// https://mvnrepository.com/artifact/org.hibernate.orm/hibernate-core
	implementation("org.hibernate.orm:hibernate-core:6.5.2.Final")

	// https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
	implementation("com.mysql:mysql-connector-j:9.5.0")
	


}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
